from typing import ClassVar

from typing import overload

class Dimensions:
    __hash__: ClassVar[None] = ...
    m: int
    n: int
    def __init__(self, arg0: int, arg1: int) -> None: ...
    def __eq__(self, arg0: Dimensions) -> bool: ...
    def __ne__(self, arg0: Dimensions) -> bool: ...

class Matrix:
    __hash__: ClassVar[None] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: float) -> None: ...
    @overload
    def __init__(self, arg0: Dimensions) -> None: ...
    @overload
    def __init__(self, arg0: Dimensions, arg1: float) -> None: ...
    @overload
    def __init__(self, arg0: Matrix) -> None: ...
    def diag(self, arg0: int) -> Matrix: ...
    def fill(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def from_list(self, arg0: list) -> None: ...
    def getSize(self) -> tuple[int,int]: ...
    def inv(self) -> Matrix: ...
    def print(self) -> None: ...
    def reserve(self, arg0: int, arg1: int) -> None: ...
    def to_list(self) -> list: ...
    def transpose(self) -> Matrix: ...
    def tril(self, arg0: int) -> Matrix: ...
    def triu(self, arg0: int) -> Matrix: ...
    def __add__(self, arg0: Matrix) -> Matrix: ...
    def __copy__(self) -> Matrix: ...
    def __deepcopy__(self, arg0: dict) -> Matrix: ...
    def __eq__(self, arg0: Matrix) -> bool: ...
    def __getitem__(self, arg0: tuple[int,int]) -> float: ...
    @overload
    def __mul__(self, arg0: Matrix) -> Matrix: ...
    @overload
    def __mul__(self, arg0: float) -> Matrix: ...
    def __ne__(self, arg0: Matrix) -> bool: ...
    def __neg__(self) -> Matrix: ...
    def __or__(self, arg0: Matrix) -> Matrix: ...
    def __setitem__(self, arg0: tuple[int,int], arg1: float) -> None: ...
    def __sub__(self, arg0: Matrix) -> Matrix: ...
    @overload
    def __truediv__(self, arg0: float) -> Matrix: ...
    @overload
    def __truediv__(self, arg0: Matrix) -> Matrix: ...

class MatrixEquationNoUniqueSolutionException(Exception): ...

class MatrixSizeDisparityException(Exception): ...

class NotSquareMatrixException(Exception): ...
